background {
    color = rgba(233, 233, 228, 1.0)
}

label {
    text = cmd[update:1000] echo "$(date +'%I:%M %p')"
    font_family = Dot 55
    font_size = 64
    color = rgba(17, 17, 17, 1.0)
    position = 0, 100
    halign = center
    valign = center
}

label {
    text = cmd[update:1000] echo "$(date +'%a %d %b')" | tr '[:lower:]' '[:upper:]'
    font_family = Dot 55
    font_size = 28
    color = rgba(17, 17, 17, 1.0)
    position = 0, 20
    halign = center
    valign = center
}

input-field {
    size = 250, 50
    outline_thickness = 2
    outer_color = rgba(17, 17, 17, 1.0)
    inner_color = rgba(233, 233, 228, 1.0)
    font_color = rgba(17, 17, 17, 1.0)
    placeholder_text = Enter Password
    position = 0, -80
    halign = center
    valign = center
}
